version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ${PSQL_VOLUME:-./data}:/var/lib/postgresql/data:z
  api:
    build: .
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=pyconkr.production_settings
      - PYCONKR_ADMIN_PASSWORD=${PYCONKR_ADMIN_PASSWORD:-pyconkr}
    command: bash docker-entrypoint.sh
    volumes:
      - .:/web
    expose:
      - "8000"
    links:
      - db
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "${PORT:-80}:80"
    volumes:
      - .:/web
      - ./static:/static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - api
